version: "1"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  server: 
    image: server
    container_name: server
    restart: always
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  client:
    image: client
    container_name: client
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - server
    volumes:
      - ../client/src:/app/src
      - ../client/index.html:/app/index.html

  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      context: ../nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "7575:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge